package com.livedoor.flow_manager.roleAuth.beans;

// Generated 2007-7-2 14:01:56 by Hibernate Tools 3.2.0.b9


/**
 * JhfCsGroupAuthorityId generated by hbm2java
 */
public class RoleAuthorityId implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -4787898706470078199L;
	
	
	private int roleId;
	private String menuSeq;

	public RoleAuthorityId() {
	}

	public RoleAuthorityId(int roleId, String menuSeq) {
		this.roleId = roleId;
		this.menuSeq = menuSeq;
	}

	public int getRoleId() {
		return roleId;
	}

	public void setRoleId(int roleId) {
		this.roleId = roleId;
	}

	public String getMenuSeq() {
		return menuSeq;
	}

	public void setMenuSeq(String menuSeq) {
		this.menuSeq = menuSeq;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((menuSeq == null) ? 0 : menuSeq.hashCode());
		result = prime * result + roleId;
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		final RoleAuthorityId other = (RoleAuthorityId) obj;
		if (menuSeq == null) {
			if (other.menuSeq != null)
				return false;
		} else if (!menuSeq.equals(other.menuSeq))
			return false;
		if (roleId != other.roleId)
			return false;
		return true;
	}


	
	
	
	
}
